### ISSUE TITLE
Weather Calendar | Render issue

### ISSUE THREAD

**Issue by kaleben0** [danielbrendel/hortusfox-web#304]
**Describe the bug**
The weather calendar no longer seems to be functioning.  

The time/condition are not aligning with the days and all have a dark circle (which I think is New Moon)

The weather API appears to be working though, because the weather on the main page is still showing and accurate. 

![image](https://github.com/user-attachments/assets/73c7809e-0fd3-4de3-93bb-dad87c7017d3)

**To Reproduce**
1. Go to 'Weather'

**Screenshots**
![Screenshot 2024-11-11 183452](https://github.com/user-attachments/assets/6553a713-a2e4-4be8-a154-cd2976a52c8b)

**Troubleshooting**
Tried a private tab, different browser and different network. No change.
Nothing in the webserver log

**Additional context**
Found this in the Dev Tools, not sure it is relevant
`Object { stack: "AxiosError@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:784:19\nhandleAbort@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:2540:14\nEventHandlerNonNull*dispatchXhrRequest@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:2535:5\nxhrAdapter<@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:2455:10\ndispatchRequest@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:3104:10\n_request@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:3386:33\nrequest@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:3253:25\nforEachMethodNoData/Axios.prototype[method]@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:3412:17\nwrap@webpack://asatruphp/./node_modules/axios/dist/browser/axios.cjs?:6:15\najaxRequest@webpack://asatruphp/./app/resources/js/app.js?:113:17\nfetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:917:24\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\nsetTimeout handler*fetchNewSystemMessage@webpack://asatruphp/./app/resources/js/app.js?:930:23\n@https://hortus.rednet.dev/weather:2606:13\nEventListener.handleEvent*@https://hortus.rednet.dev/weather:2510:11\n", message: "Request aborted", name: "AxiosError", code: "ECONNABORTED", config: {…}, request: XMLHttpRequest }
app.js:118:29
`

**Comment by kaleben0** [comment]
Here is an export fo the CacheModel table from the db. 
It looks like the database is propagating. 
[CacheModel.csv](https://github.com/user-attachments/files/17709388/CacheModel.csv)

**Comment by danielbrendel** [comment]
It should be fixed now, but I'll leave this open for now, just to be sure and occassionally check if it now takes DST into account now.

**Comment by kaleben0** [comment]
Looks Good!

**Comment by dghoti** [comment]
I am still getting this from an earlier install, but updated to :
HortusFox v3.7
PHP Version: 8.3.0
MySQL Version: 11.5.2-MariaDB-ubu2404
Server: Linux #1 SMP PREEMPT Debian 1:6.6.51-1+rpt1 (2024-09-26) on aarch64
Timezone: 2024-11-17 17:47 (Europe/Dublin)
I have cleared cookies/site data, but no joy.
Is there a way to also backup accounts - as well as the data?

**Comment by danielbrendel** [comment]
Will be worked on via #309
