### ISSUE TITLE
WEather Forcast incorrect/corrupted

### ISSUE THREAD

**Issue by dghoti** [danielbrendel/hortusfox-web#306]
**Describe the bug**
The weather is only showing as blank circles and no data/weather

**To Reproduce**
1. Configure and install a new, blank docker-compose file
2. add existing and tested working weather api info
3. click on "weather icon" on upper toolbar

**Expected behavior**
To see a weather forcast (the weather/location name shows fine in corner of main page, as expected.

**Screenshots**
![image](https://github.com/user-attachments/assets/e2f1e67e-f5fe-4949-bad9-9eff0b051b89)

**Software:**
HortusFox v3.7
PHP Version: 8.3.0
MySQL Version: 11.5.2-MariaDB-ubu2404
Server: Linux #1 SMP PREEMPT Debian 1:6.6.51-1+rpt1 (2024-09-26) on aarch64
Timezone: 2024-11-17 19:08 (Europe/Dublin)
Render time: 1.0942s
- Changes to your docker-compose file if altered
Have only edited username/password , also changed to fixed location volumes inside docker compose folder

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win11
 - Browser [e.g. chrome, safari] Current Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] pixel 5
 - OS: [e.g. iOS8.1] Android 14
 - Browser [e.g. stock browser, safari] stock chrome

**Additional context**
when enabling/disabling openweather info, I get the following error:
![image](https://github.com/user-attachments/assets/a9f28049-5c41-4d6f-bc88-5827b8e88023)

**Comment by danielbrendel** [comment]
Hi, the fix for DST will be available in v3.8, so it is not available via
the current version 3.7.
But nonetheless you raised an important issue here in your screenshot!

Due to strict mode, mariadb fails to update the cache using 1970-01-01
00:00:00 as value for updated_at in the cache model, so as a result the
cache will never be updated and as such you will keep seeing old weather
data.

The v3.8 hotfix update is scheduled for the up-coming weekend (Friday or
Saturday), so stay tuned! Unfortunately I can't release the hotfix version
before since Mo-Thu are very busy days.

Thanks for reporting this issue!

**Comment by dghoti** [comment]
Thank you kindly!

**Comment by danielbrendel** [comment]
Resolved with current release.

**Comment by dghoti** [comment]
Started a new instance - added the weathermap API - bug still present
